# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0003_auto_20160628_2156')
    ]

    database_operations = [
        migrations.AlterModelTable('Violation', 'event_event'),
        migrations.AlterModelTable('ViolationStartDate', 'event_eventstartdate'),
        migrations.AlterModelTable('ViolationEndDate', 'event_eventenddate'),
        migrations.AlterModelTable('ViolationLocationDescription', 'event_eventlocationdescription'),
        migrations.AlterModelTable('ViolationAdminLevel1', 'event_eventadminlevel1'),
        migrations.AlterModelTable('ViolationAdminLevel2', 'event_eventadminlevel2'),
        migrations.AlterModelTable('ViolationGeoname', 'event_eventgeoname'),
        migrations.AlterModelTable('ViolationGeonameId', 'event_eventgeonameid'),
        migrations.AlterModelTable('ViolationLocation', 'event_eventlocation'),
        migrations.AlterModelTable('ViolationDescription', 'event_eventdescription'),
        migrations.AlterModelTable('ViolationPerpetrator', 'event_eventperpetrator'),
        migrations.AlterModelTable('ViolationPerpetratorOrganization', 'event_eventperpetratororganization'),
        migrations.AlterModelTable('ViolationType', 'event_eventtype'),
        migrations.AlterModelTable('Type', 'event_type'),
    ]

    state_operations = [
        migrations.DeleteModel('Violation'),
        migrations.DeleteModel('ViolationStartDate'),
        migrations.DeleteModel('ViolationEndDate'),
        migrations.DeleteModel('ViolationLocationDescription'),
        migrations.DeleteModel('ViolationAdminLevel1'),
        migrations.DeleteModel('ViolationAdminLevel2'),
        migrations.DeleteModel('ViolationGeoname'),
        migrations.DeleteModel('ViolationGeonameId'),
        migrations.DeleteModel('ViolationLocation'),
        migrations.DeleteModel('ViolationDescription'),
        migrations.DeleteModel('ViolationPerpetrator'),
        migrations.DeleteModel('ViolationPerpetratorOrganization'),
        migrations.DeleteModel('ViolationType'),
        migrations.DeleteModel('Type'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
